# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'initial.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QGroupBox, QPushButton,
    QSizePolicy, QWidget)
import buttonsGlassRound_rc

class Ui_tab_initial_setup(object):
    def setupUi(self, tab_initial_setup):
        if not tab_initial_setup.objectName():
            tab_initial_setup.setObjectName(u"tab_initial_setup")
        tab_initial_setup.resize(235, 110)
        tab_initial_setup.setWindowTitle(u"tab_initial_setup")
        self.groupBox_exit = QGroupBox(tab_initial_setup)
        self.groupBox_exit.setObjectName(u"groupBox_exit")
        self.groupBox_exit.setGeometry(QRect(0, 0, 81, 102))
#if QT_CONFIG(tooltip)
        self.groupBox_exit.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.groupBox_exit.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.groupBox_exit.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.groupBox_exit.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.groupBox_exit.setTitle(u"")
        self.gridLayoutWidget = QWidget(self.groupBox_exit)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 10, 67, 81))
        self.gridLayout_exit = QGridLayout(self.gridLayoutWidget)
        self.gridLayout_exit.setSpacing(0)
        self.gridLayout_exit.setObjectName(u"gridLayout_exit")
        self.gridLayout_exit.setContentsMargins(0, 0, 0, 0)
        self.pushButton_title_exit = QPushButton(self.gridLayoutWidget)
        self.pushButton_title_exit.setObjectName(u"pushButton_title_exit")
        self.pushButton_title_exit.setMinimumSize(QSize(65, 0))
        font = QFont()
        font.setBold(True)
        self.pushButton_title_exit.setFont(font)
#if QT_CONFIG(tooltip)
        self.pushButton_title_exit.setToolTip(u"Exit")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_title_exit.setStatusTip(u"Exit")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pushButton_title_exit.setWhatsThis(u"Exit")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.pushButton_title_exit.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.pushButton_title_exit.setStyleSheet(u"background:rgb(165, 29, 45)")
        self.pushButton_title_exit.setText(u"Exit")
        icon = QIcon()
        icon.addFile(u":/buttons/buttons/glassRound/glassButtonExit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_title_exit.setIcon(icon)

        self.gridLayout_exit.addWidget(self.pushButton_title_exit, 1, 0, 1, 1, Qt.AlignHCenter)

        self.pushButtonExit = QPushButton(self.gridLayoutWidget)
        self.pushButtonExit.setObjectName(u"pushButtonExit")
        self.pushButtonExit.setMinimumSize(QSize(50, 50))
        self.pushButtonExit.setMaximumSize(QSize(50, 50))
#if QT_CONFIG(tooltip)
        self.pushButtonExit.setToolTip(u"Exit Application")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButtonExit.setStatusTip(u"Exit Application")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pushButtonExit.setWhatsThis(u"Exit Application")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.pushButtonExit.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.pushButtonExit.setLayoutDirection(Qt.LeftToRight)
        self.pushButtonExit.setText(u"")
        self.pushButtonExit.setIcon(icon)
        self.pushButtonExit.setIconSize(QSize(48, 48))
#if QT_CONFIG(shortcut)
        self.pushButtonExit.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButtonExit.setFlat(True)

        self.gridLayout_exit.addWidget(self.pushButtonExit, 0, 0, 1, 1, Qt.AlignHCenter)

        self.groupBox_navigation = QGroupBox(tab_initial_setup)
        self.groupBox_navigation.setObjectName(u"groupBox_navigation")
        self.groupBox_navigation.setGeometry(QRect(90, 0, 151, 102))
#if QT_CONFIG(tooltip)
        self.groupBox_navigation.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.groupBox_navigation.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.groupBox_navigation.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.groupBox_navigation.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.groupBox_navigation.setTitle(u"")
        self.gridLayoutWidget_2 = QWidget(self.groupBox_navigation)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(10, 10, 131, 81))
        self.gridLayout_navigation = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_navigation.setSpacing(0)
        self.gridLayout_navigation.setObjectName(u"gridLayout_navigation")
        self.gridLayout_navigation.setContentsMargins(0, 0, 0, 0)
        self.pushButton_navigation_previous = QPushButton(self.gridLayoutWidget_2)
        self.pushButton_navigation_previous.setObjectName(u"pushButton_navigation_previous")
        self.pushButton_navigation_previous.setMinimumSize(QSize(50, 50))
        self.pushButton_navigation_previous.setMaximumSize(QSize(50, 50))
#if QT_CONFIG(tooltip)
        self.pushButton_navigation_previous.setToolTip(u"Previous Page")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_navigation_previous.setStatusTip(u"Previous Page")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pushButton_navigation_previous.setWhatsThis(u"Previous Page")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.pushButton_navigation_previous.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.pushButton_navigation_previous.setText(u"")
        icon1 = QIcon()
        icon1.addFile(u":/buttons/buttons/glassRound/glassButtonPrevious.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_navigation_previous.setIcon(icon1)
        self.pushButton_navigation_previous.setIconSize(QSize(48, 48))
#if QT_CONFIG(shortcut)
        self.pushButton_navigation_previous.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_navigation_previous.setFlat(True)

        self.gridLayout_navigation.addWidget(self.pushButton_navigation_previous, 0, 0, 1, 1)

        self.pushButton_navigation_next = QPushButton(self.gridLayoutWidget_2)
        self.pushButton_navigation_next.setObjectName(u"pushButton_navigation_next")
        self.pushButton_navigation_next.setMinimumSize(QSize(50, 50))
        self.pushButton_navigation_next.setMaximumSize(QSize(50, 50))
#if QT_CONFIG(tooltip)
        self.pushButton_navigation_next.setToolTip(u"Next Page")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_navigation_next.setStatusTip(u"Next Page")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pushButton_navigation_next.setWhatsThis(u"Next Page")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.pushButton_navigation_next.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.pushButton_navigation_next.setText(u"")
        icon2 = QIcon()
        icon2.addFile(u":/buttons/buttons/glassRound/glassButtonNext.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_navigation_next.setIcon(icon2)
        self.pushButton_navigation_next.setIconSize(QSize(48, 48))
        self.pushButton_navigation_next.setFlat(True)

        self.gridLayout_navigation.addWidget(self.pushButton_navigation_next, 0, 1, 1, 1)

        self.pushButton_title_navigation = QPushButton(self.gridLayoutWidget_2)
        self.pushButton_title_navigation.setObjectName(u"pushButton_title_navigation")
        self.pushButton_title_navigation.setMinimumSize(QSize(65, 0))
        self.pushButton_title_navigation.setFont(font)
#if QT_CONFIG(tooltip)
        self.pushButton_title_navigation.setToolTip(u"Exit")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_title_navigation.setStatusTip(u"Exit")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pushButton_title_navigation.setWhatsThis(u"Exit")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.pushButton_title_navigation.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.pushButton_title_navigation.setStyleSheet(u"background:rgb(38, 162, 105)")
        self.pushButton_title_navigation.setText(u"Navigation")
        self.pushButton_title_navigation.setIcon(icon)

        self.gridLayout_navigation.addWidget(self.pushButton_title_navigation, 1, 0, 1, 2, Qt.AlignHCenter)


        self.retranslateUi(tab_initial_setup)

        QMetaObject.connectSlotsByName(tab_initial_setup)
    # setupUi

    def retranslateUi(self, tab_initial_setup):
        pass
    # retranslateUi

